### ISSUE TITLE
Oh My Zsh updates not being checked

### ISSUE THREAD

**Issue by shyun3** [getantidote/use-omz#7]
I'm using the `reminder` method of Oh My Zsh auto-update and I've found that when using `use-omz`, I no longer get reminders to update Oh My Zsh. Is there a way this behavior can be restored?

**Comment by mattmc3** [comment]
I pushed a commit that should resolve this for you. If not, let me know and I'll re-open.

**Comment by shyun3** [comment]
I tried activating traces around your change to make sure that the check was being run and it looks like there's a test that's failing?
```
+/home/mhyun/.cache/antidote/getantidote/use-omz/use-omz.zsh:111> source /home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:2> [[ -f /home/mhyun/.zsh-update ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:14> zstyle -s :omz:update mode update_mode
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:28> [[ reminder = disabled ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:29> [[ ! -w /home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh || ! -O /home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:30> [[ ! -t 1 && off == off ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:33> unset update_mode
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:34> return
+/home/mhyun/.cache/antidote/getantidote/use-omz/use-omz.zsh:112> set +x
```

**Comment by mattmc3** [comment]
`[[ ! -t 1 && off == off ]]` is hit because it's not being run from an interactive session (meaning you called a subshell or ran it in a script). That's an OMZ condition, not anything this plugin is doing. What happens when you run your traces directly from your .zshrc? What problem are you seeing?

**Comment by shyun3** [comment]
Ok, I placed the traces in my `.zshrc` as follows:
```zsh
if [[ -f ~/.antidote/antidote.zsh ]]; then
  source ~/.antidote/antidote.zsh
  set -x
  antidote load
  set +x
fi
```

This resulted in a lot of output on the start of a new shell. Here is the relevant part of the trace:
```
+/home/mhyun/.cache/antidote/getantidote/use-omz/use-omz.zsh:110> source /home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:2> [[ -f /home/mhyun/.zsh-update ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:14> zstyle -s :omz:update mode update_mode
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:28> [[ reminder = disabled ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:29> [[ ! -w /home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh || ! -O /home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:30> [[ ! -t 1 && off == off ]]
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:33> unset update_mode
+/home/mhyun/.cache/antidote/ohmyzsh/ohmyzsh/tools/check_for_upgrade.sh:34> return
```
It looks like the test is still failing.
